version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
  scoreboard:
    image: dapplegate/scoreboard
    build: ./
    hostname: ${HOSTNAME}
    labels:
      caddy: ${HOSTNAME}
      caddy.reverse_proxy: "{{ upstreams 8000 }}"
    volumes:
      - ./app:/app
      - scoreboard_data:/app/data
    restart: unless-stopped

volumes:
  caddy_data: {}
  scoreboard_data: {}
